# Generated by Django 5.2 on 2025-04-15 07:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='users/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('st', 'student'), ('wd', 'warden'), ('pt', 'parents'), ('gt', 'guests')], max_length=2)),
            ],
        ),
    ]
