# Generated by Django 5.2 on 2025-04-15 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('roll_number', models.CharField(max_length=50, unique=True)),
                ('photo', models.ImageField(upload_to='user_photos/')),
                ('gender', models.CharField(max_length=10)),
                ('degree', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField()),
                ('password', models.CharField(max_length=100)),
                ('dob', models.DateField()),
            ],
        ),
    ]
